[project]
name = "thesis-summary-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "anthropic>=0.45.0",
    "boto3>=1.35.97",
    "langchain>=0.3.14",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.1",
]
